### ISSUE TITLE
Entrega Trabajo Práctico N°1

### ISSUE THREAD

**Issue by donalavalle** [donalavalle/2020_k2031_Grupo_1#1]
solicitamos la corrección del trabajo practico N°1 @santiagoferreiros

**Comment by donalavalle** [comment]
Solicitamos *

**Comment by santiagoferreiros** [comment]
@donalavalle @AgusB1101 @Octiperalta @raquellacruz06 

Estimados, EXCELENTE TRABAJO ! Muy bien
Nota 10

Felicitaciones
No tengo observaciones para realizar. Lo único, que dentro de la carpeta no me pusieron el archivo "Entrada.txt" para probar directamente. Pero es un detalle, siempre incluyan archivos de prueba que utilizaron a modo de testing.
