### ISSUE TITLE
Entrega Trabajo Práctico N°2

### ISSUE THREAD

**Issue by AgusB1101** [donalavalle/2020_k2031_Grupo_1#2]
Solicitamos la corrección del Trabajo Práctico N°2 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados !

Muy buen trabajo =)
Nota: 8

La funcionalidad perfecta.
No clasifica errores. Eso sería el bonus para el 10
Además tienen la tabla de transición pero no la utilizan como tal.

Han implementado la TT pero a medias. Supuestamente la información del push ya está cargada dentro de la tabla. Por lo que vi, ustedes utilizaron varias IF y ELSE para decidir que pushear en cada caso. Es decir, que guardaron información en la TT que después no usan porque lo preguntan en los IF cuando dicen si estoy en la caracter tal y leí tal caracter, hago tal push.

Por ejemplo

 if(estadoActual == Q0) 
            {
                if(caracterLeido == ParenthesesOpen)    // Si lee un '('
                {
                    pushStack(&stack, elemCima);    
                    pushStack(&stack, 'R');
                }
                else
                    pushStack(&stack, elemCima); 
            }

No terminan consultando la TT. Directamente lo preguntan con if.

Saludos,

Santiago

@AgusB1101 @Octiperalta @donalavalle @raquellacruz06
