### ISSUE TITLE
Entrega Trabajo Práctico Nº3

### ISSUE THREAD

**Issue by AgusB1101** [donalavalle/2020_k2031_Grupo_1#3]
Solicitamos la corrección del Trabajo Práctico N°3 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimados,

EXCELENTE TRABAJO.
Lo único, me parece que no están capturando las tabulaciones

![image](https://user-images.githubusercontent.com/46604718/88959305-29f43480-d278-11ea-8101-139069a40f63.png)

Por lo que veo en el reporte parece que los espacios y tabulaciones están generando todas esas salidas.

Puede resivarlo para que ya les quede lista esta parte para el TP integrador.

Saludos, y FELICITACIONES ! =)

Santiago
