### ISSUE TITLE
Entrega Trabajo Práctico N°4

### ISSUE THREAD

**Issue by belenbusca** [donalavalle/2020_k2031_Grupo_1#4]
Solicitamos la corrección del Trabajo Práctico N°4 @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Estimado grupo,

Excelente trabajo. He leído sus comentarios del archivo de prueba :)
Tengo un perro, que no se lleva bien con los gatos jaja

Sigan trabajando para el trabajo práctico integrador.

Lo que si les sugiero es que agreguen en número de línea en el reporte de cada cosa que encuentra. Es una forma más rápida de rastrear lo que sucede. Les va a ser de utilidad para el TPI.

Pueden tomar el número de línea desde flex cuando lee un '\n'

Nota: 9

Vamos por más !
Entrega aprobada

Santiago
